export enum WaitingRoomEvents {
    AcceptPlayer = 'acceptPlayer',
    RejectPlayer = 'rejectPlayer',
    AbortGameCreation = 'abortGameCreation',
    LeaveGame = 'leaveGame',
    Start = 'start',
    Started = 'started',
    CreateGame = 'createGame',
    AskingToJoinGame = 'askingToJoinGame',
    GameInfo = 'gameInfo',
    GameCreated = 'gameCreated',
    PlayerRejected = 'playerRejected',
    PlayerAccepted = 'playerAccepted',
    GameCanceled = 'gameCanceled',
    GameFound = 'gameFound',
    GameDeleted = 'gameDeleted',
}
